version: '2'
services:
  fluentbit:
    image: fluent/fluent-bit:1.1
    restart: always
    environment:
      MQTT_LISTEN_ADDR: 0.0.0.0
      MQTT_PORT: 8884
      INFLUXDB_HOST: influxdb
      INFLUXDB_PORT: 8086
      INFLUXDB_DB: iotdata
    volumes:
      - $PWD/etc/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "8884:8884"
  influxdb:
    image: influxdb:latest
    restart: always
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_DB: iotdata
    volumes:
      - $PWD/var/lib/influxdb:/var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
  grafana:
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - influxdb
    volumes:
      - $PWD/var/lib/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
